### ISSUE TITLE
About the device and training time.

### ISSUE THREAD

**Issue by abcdvzz** [17Skye17/VideoLT#1]
Hi there, I noticed that you did not post the device and time information on your paper. I am considering following this work but I am not sure if my device can handle this task. Could you pls tell me the corresponding information? Like the type of GPU and training time. Thank you very much.

**Comment by 17Skye17** [comment]
> Hi there, I noticed that you did not post the device and time information on your paper. I am considering following this work but I am not sure if my device can handle this task. Could you pls tell me the corresponding information? Like the type of GPU and training time. Thank you very much.

Hi, thank you for your interest in our work.

1.  We conduct all experiments under 4 1080ti gpus. 

2.  Training a Nonlinear model or NetVLAD model takes about 1.5 days using 1 1080Ti gpu, the features of dataset are stored in a 1T SSD.

Note that since there are about 256k videos, you may need SSD for faster  I/O or the training speed will decrease at about 5 times using a HDD. (maybe you could search for more efficient implementation of dataloader).

**Comment by 17Skye17** [comment]
Feel free to reopen this issue if you have further questions, enjoy your day.
